version: 2

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/blast
    binary: blast
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

brews:
  - repository:
      owner: doganarif
      name: homebrew-blast
    directory: Formula
    homepage: https://github.com/doganarif/blast
    description: "Zero-config local HTTPS reverse proxy for development"
    license: MIT
    caveats: |
      Blast requires root privileges to run.

      Get started:
        sudo blast start 3000 myapp

      Then visit: https://myapp.blast

      Firefox users: Run 'blast ca-path' for setup instructions.
